export const YYYY_MM_DD = "YYYY/MM/DD"
export const YYYY_M_D = "YYYY/M/D"
export const YY_MM_DD = "YY/MM/DD"
export const YY_MM = "YY/MM"
export const MM_DD = "MM/DD"
export const YYYY_MM = "YYYY/MM"
export const DATE_FULL = "YYYY/MM/DD HH:mm:ss"
